#!/usr/bin/env ruby

@bootstrap = image {
  stage "bootstrap", "wkndr:latest"

  command("COPY") {
    "Wkndrfile /var/lib/wkndr/"
  }

  command("COPY") {
    "public/chicken-maze-prototype /var/lib/wkndr/public/chicken-maze-prototype"
  }
}
