apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
cloudProvider: aws
networking:
  dnsDomain: bardin.haus
api:
  advertiseAddress: kubernetes.default.svc.bardin.haus
  bindPort: 6443
apiServerExtraArgs:
  "external-hostname": kubernetes.default.svc.bardin.haus
