apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
cloudProvider: aws
nodeName: ip-10-0-0-253.us-west-1.compute.internal
#api:
#  advertiseAddress: kubernetes.bardin.haus
#apiServerExtraArgs:
#  "external-hostname": kubernetes.bardin.haus
controllerManagerExtraArgs:
  "allow-untagged-cloud": "true"
#apiServerCertSANs:
#  - 13.56.150.135
