---
- hosts: localhost
  connection: local
  vars_files:
    - vars/bardin-haus.yml
  tasks:
    - name: determine public ip
      shell: "dig +short myip.opendns.com @resolver1.opendns.com"
      register: public_ip_result

    - set_fact:
        public_ip: "{{ public_ip_result.stdout }}"

    - debug: msg="{{ public_ip }}"

    - ec2_vpc_net:
        name: bardin-haus 
        cidr_block: 10.0.0.0/24
        region: us-west-1
        tags:
          Name: bardin-haus
        tenancy: default
      register: provisioned_vpc

    - ec2_vpc_subnet:
        state: present
        vpc_id: "{{ provisioned_vpc.vpc.id }}"
        cidr: "10.0.0.0/24"
        az: us-west-1a
        region: us-west-1
        resource_tags:
          Name: bardin-haus-a
      register: provisioned_subnet

    - ec2_group:
        name: "{{ bardin_haus_ec2_group }}"
        description: allows SSH and HTTP/S only
        vpc_id: "{{ provisioned_vpc.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ public_ip }}/32"
          - proto: tcp
            from_port: 6443
            to_port: 6443
            cidr_ip: "{{ public_ip }}/32"
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 5100
            to_port: 5100
            cidr_ip: 0.0.0.0/0

    #- fail: msg="halt"

    #TODO: automate => instance_profile_name: kubernetes
    - ec2:
        user_data: "{{ lookup('file', 'files/user_data.sh') }}"
        assign_public_ip: true
        vpc_subnet_id: "{{ provisioned_subnet.subnet.id }}"
        instance_type: t2.medium
        image: "{{ bardin_haus_ami }}"
        keypair: "{{ lookup('ENV', 'EC2_KEYPAIR') }}"
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: "60"
        exact_count: 1
        wait: yes
        group: "{{ bardin_haus_ec2_group }}"
        instance_tags:
          Name: "{{ bardin_haus_instance_name }}"
        count_tag:
          Name: "{{ bardin_haus_instance_name }}"
      register: instance

    - name: "provision naked DNS"
      route53:
        command: create
        zone: "{{ bardin_haus_naked_domain }}"
        record: "{{ bardin_haus_naked_domain }}"
        type: A
        ttl: 60
        value: "{{ instance.tagged_instances[0].public_ip }}"
        overwrite: true

    - name: "provision wildcard DNS"
      route53:
        command: create
        zone: "{{ bardin_haus_naked_domain }}"
        record: "*.{{ bardin_haus_naked_domain }}"
        type: CNAME
        ttl: 60
        value: "{{ bardin_haus_naked_domain }}"
        overwrite: true

    - name: "set bardin_haus_host"
      set_fact:
        bardin_haus_host: "{{ instance.tagged_instances[0].public_ip }}"

    - name: "create bardin-haus inventory"
      template: src=templates/inventory.j2 dest=inventory/bardin-haus

    - name: Wait for SSH to come up
      wait_for: host={{ bardin_haus_host }} port={{ ansible_port|default(22) }} connect_timeout=1 timeout=30 state=started

#    - name: add known hosts
#      shell: "grep '{{ bardin_haus_host }} ' ~/.ssh/known_hosts || ssh-keyscan {{ bardin_haus_host }} >> ~/.ssh/known_hosts"
